### ISSUE TITLE
Error: no schema with key or ref "https://json-schema.org/draft/2020-12/schema"

### ISSUE THREAD

**Issue by Olaf-Wolf3D** [walbo/validate-json#299]
My schemas use this `$schema` definition:

```
"$schema": "https://json-schema.org/draft/2020-12/schema",
```

Using your action with 

```
jobs:
  validate:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Validate JSON Schemas
          uses: walbo/validate-json@v1.1.0
          with:
            files: schemas/**/*.schema.json
```

results in the failed action.

>Error: no schema with key or ref "https://json-schema.org/draft/2020-12/schema"

Why? When you follow the link, it's clearly a (meta) schema.
